eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka
    register-with-eureka: true
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8761