spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yyjgit66/config-repo.git
          username: yyjgit66
          password: yyj123456oo
          basedir: F:\配置中心配置
   #rabbitmq消息队列配置      
  rabbitmq:
    host: 192.168.1.5
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web: 
      exposure:
        include: "*"
server:
  port: 8082